package gochunk

import (
	"context"
	"reflect"
	"testing"

	"github.com/go-go-golems/ragkit/digest"
	"github.com/go-go-golems/ragkit/rag"
)

func TestExtractorPreservesDeclarationRangesAndMetadata(t *testing.T) {
	t.Parallel()
	text := "// Package trees handles trees.\npackage trees\n\n// Oak is a tree.\ntype Oak struct{}\n\n// Grow grows.\nfunc (o *Oak) Grow(n int) error { return nil }\n"
	document := fixtureDocument(text, "trees.go")
	records, diagnostics, err := (Extractor{}).Extract(context.Background(), document)
	if err != nil {
		t.Fatalf("Extract() error = %v", err)
	}
	if len(diagnostics) != 0 {
		t.Fatalf("diagnostics = %#v", diagnostics)
	}
	if len(records) != 3 {
		t.Fatalf("records = %d, want 3", len(records))
	}
	method := records[2]
	if method.Metadata.Kind != "method" || method.Metadata.Receiver != "*Oak" || method.Metadata.Name != "Grow" {
		t.Fatalf("method metadata = %#v", method.Metadata)
	}
	if method.Metadata.LineStart != 7 || method.Metadata.LineEnd != 8 {
		t.Fatalf("method lines = %d-%d, want 7-8", method.Metadata.LineStart, method.Metadata.LineEnd)
	}
	if method.Chunk.Text != text[method.Chunk.Range.ByteStart:method.Chunk.Range.ByteEnd] {
		t.Fatal("method text does not match exact source range")
	}
	if err := method.Validate(document); err != nil {
		t.Fatalf("Validate() error = %v", err)
	}
}
func TestExtractorKeepsSyntaxRecordsWithDiagnostics(t *testing.T) {
	t.Parallel()
	document := fixtureDocument("package broken\nfunc Good() {}\nfunc Bad( {\n", "broken.go")
	records, diagnostics, err := (Extractor{}).Extract(context.Background(), document)
	if err != nil {
		t.Fatalf("Extract() error = %v", err)
	}
	if len(diagnostics) == 0 {
		t.Fatal("diagnostics are empty")
	}
	if len(records) == 0 || records[0].Metadata.ParseStatus != "syntax-errors" {
		t.Fatalf("records = %#v", records)
	}
}
func TestExtractorClassifiesTests(t *testing.T) {
	t.Parallel()
	document := fixtureDocument("package trees\nimport \"testing\"\nfunc TestOak(t *testing.T) {}\nfunc BenchmarkOak(b *testing.B) {}\nfunc FuzzOak(f *testing.F) {}\nfunc ExampleOak() {}\n", "trees_test.go")
	records, _, err := (Extractor{}).Extract(context.Background(), document)
	if err != nil {
		t.Fatalf("Extract() error = %v", err)
	}
	want := []string{"test", "benchmark", "fuzz", "example"}
	if len(records) != len(want) {
		t.Fatalf("records = %d, want %d", len(records), len(want))
	}
	for index := range want {
		if records[index].Metadata.Kind != want[index] || !records[index].Metadata.Test {
			t.Fatalf("record %d metadata = %#v", index, records[index].Metadata)
		}
	}
}
func TestExtractorOutputOrderIsDeterministic(t *testing.T) {
	t.Parallel()
	document := fixtureDocument("// Package trees contains tree helpers.\npackage trees\n// Oak is a tree.\ntype Oak struct{}\n\nconst Height = 3\n\nfunc Grow() {}\n", "trees.go")
	firstRecords, firstDiagnostics, err := (Extractor{}).Extract(context.Background(), document)
	if err != nil {
		t.Fatalf("first Extract() error = %v", err)
	}
	secondRecords, secondDiagnostics, err := (Extractor{}).Extract(context.Background(), document)
	if err != nil {
		t.Fatalf("second Extract() error = %v", err)
	}
	if !reflect.DeepEqual(firstDiagnostics, secondDiagnostics) {
		t.Fatalf("diagnostics differ: first=%#v second=%#v", firstDiagnostics, secondDiagnostics)
	}
	if !reflect.DeepEqual(firstRecords, secondRecords) {
		t.Fatalf("records differ: first=%#v second=%#v", firstRecords, secondRecords)
	}
	wantNames := []string{"trees", "Oak", "Height", "Grow"}
	if len(firstRecords) != len(wantNames) {
		t.Fatalf("records = %d, want %d", len(firstRecords), len(wantNames))
	}
	for index, want := range wantNames {
		if got := firstRecords[index].Metadata.Name; got != want {
			t.Fatalf("record %d name = %q, want %q", index, got, want)
		}
	}
}
func TestRepresentationsHaveRawAndSymbolPerChunk(t *testing.T) {
	t.Parallel()
	document := fixtureDocument("package trees\n// Oak is a tree.\ntype Oak struct{}\n", "trees.go")
	records, _, err := (Extractor{}).Extract(context.Background(), document)
	if err != nil {
		t.Fatalf("Extract() error = %v", err)
	}
	representations, err := Representations(records)
	if err != nil {
		t.Fatalf("Representations() error = %v", err)
	}
	if len(representations) != len(records)*2 {
		t.Fatalf("representations = %d, want %d", len(representations), len(records)*2)
	}
	if representations[0].Kind != "raw" || representations[len(records)].Kind != "symbol" {
		t.Fatalf("representation kinds = %q, %q", representations[0].Kind, representations[len(records)].Kind)
	}
}
func TestGeneratedMarker(t *testing.T) {
	t.Parallel()
	if !IsGenerated("// Code generated by tool; DO NOT EDIT.\npackage x\n") {
		t.Fatal("standard generated marker not recognized")
	}
	if IsGenerated("// generated manually\npackage x\n") {
		t.Fatal("non-standard marker recognized")
	}
}
func TestFixedAllPreservesMetadataAndLines(t *testing.T) {
	t.Parallel()
	document := fixtureDocument("package trees\nfunc Oak() {}\nfunc Pine() {}\n", "trees.go")
	records, diagnostics, err := FixedAll(context.Background(), []rag.Document{document}, 20, 2)
	if err != nil {
		t.Fatalf("FixedAll() error = %v", err)
	}
	if len(diagnostics) != 0 || len(records) < 2 {
		t.Fatalf("records = %d, diagnostics = %#v", len(records), diagnostics)
	}
	for _, record := range records {
		if record.Metadata.Kind != "fixed" || record.Metadata.PackageName != "trees" {
			t.Fatalf("metadata = %#v", record.Metadata)
		}
		if err := record.Validate(document); err != nil {
			t.Fatalf("Validate() error = %v", err)
		}
	}
}
func fixtureDocument(text, path string) rag.Document {
	return rag.Document{ID: "doc-1", SourceURI: "git://example/" + path, Title: path, Text: text, ContentDigest: digest.Text(text), Metadata: map[string]string{"repository": "example", "commit": "0123456789ab", "path": path, "package_path": "example.org/project/trees"}}
}
