package gochunk

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestLoadCommittedIgnoresDirtyWorktreeAndGeneratedFiles(t *testing.T) {
	repository := t.TempDir()
	writeFixture(t, filepath.Join(repository, "go.mod"), "module example.org/fixture\n\ngo 1.26\n")
	writeFixture(t, filepath.Join(repository, "pkg", "oak.go"), "package pkg\nfunc Oak() string { return \"committed\" }\n")
	writeFixture(t, filepath.Join(repository, "pkg", "generated.go"), "// Code generated by fixture; DO NOT EDIT.\npackage pkg\n")
	runGit(t, repository, "init", "-q")
	runGit(t, repository, "config", "user.email", "fixture@example.com")
	runGit(t, repository, "config", "user.name", "Fixture")
	runGit(t, repository, "add", ".")
	runGit(t, repository, "commit", "-qm", "fixture")
	writeFixture(t, filepath.Join(repository, "pkg", "oak.go"), "package pkg\nfunc Oak() string { return \"dirty\" }\n")
	workspace := t.TempDir()
	manifestPath := filepath.Join(workspace, "wsm.json")
	manifest := map[string]any{"path": workspace, "repositories": []map[string]string{{"name": "fixture", "worktreePath": repository}}}
	body, err := json.Marshal(manifest)
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, manifestPath, string(body))
	result, err := LoadCommitted(context.Background(), manifestPath, DefaultPolicy())
	if err != nil {
		t.Fatalf("LoadCommitted() error = %v", err)
	}
	if len(result.Documents) != 1 {
		t.Fatalf("documents = %d, want 1", len(result.Documents))
	}
	if got := result.Documents[0].Text; got != "package pkg\nfunc Oak() string { return \"committed\" }\n" {
		t.Fatalf("document text = %q", got)
	}
	if result.Documents[0].Metadata["package_path"] != "example.org/fixture/pkg" {
		t.Fatalf("package path = %q", result.Documents[0].Metadata["package_path"])
	}
	if len(result.Admissions) != 2 || result.Admissions[0].Reason != "generated" {
		t.Fatalf("admissions = %#v", result.Admissions)
	}
	if result.Snapshot.Digest == "" || len(result.Snapshot.Repositories) != 1 {
		t.Fatalf("snapshot = %#v", result.Snapshot)
	}
}

func TestDecideAdmissionAppliesTestdataLimitAtRepositoryRoot(t *testing.T) {
	policy := Policy{MaximumFileBytes: 100, MaximumTestdataBytes: 4}
	for _, path := range []string{"testdata/large.go", "pkg/testdata/large.go"} {
		admission := decideAdmission("repo", "commit", path, []byte("12345"), policy)
		if admission.Admitted || admission.Reason != "testdata-too-large" {
			t.Fatalf("%s admission = %#v", path, admission)
		}
	}
}

func TestCommittedReadsUseTheResolvedCommit(t *testing.T) {
	repository := t.TempDir()
	writeFixture(t, filepath.Join(repository, "go.mod"), "module example.org/old\n")
	writeFixture(t, filepath.Join(repository, "pkg", "old.go"), "package pkg\n")
	runGit(t, repository, "init", "-q")
	runGit(t, repository, "config", "user.email", "fixture@example.com")
	runGit(t, repository, "config", "user.name", "Fixture")
	runGit(t, repository, "add", ".")
	runGit(t, repository, "commit", "-qm", "old")
	head, err := repositoryHead(context.Background(), "fixture", repository)
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, filepath.Join(repository, "go.mod"), "module example.org/new\n")
	writeFixture(t, filepath.Join(repository, "pkg", "new.go"), "package pkg\n")
	runGit(t, repository, "add", ".")
	runGit(t, repository, "commit", "-qm", "new")
	module, err := repositoryModulePath(context.Background(), repository, head.Commit)
	if err != nil {
		t.Fatal(err)
	}
	paths, err := trackedPaths(context.Background(), repository, head.Commit)
	if err != nil {
		t.Fatal(err)
	}
	if module != "example.org/old" || len(paths) != 2 || paths[1] != "pkg/old.go" {
		t.Fatalf("resolved commit read = module %q paths %#v", module, paths)
	}
}
func writeFixture(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
func runGit(t *testing.T, repository string, arguments ...string) {
	t.Helper()
	command := exec.Command("git", append([]string{"-C", repository}, arguments...)...)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v: %s", arguments, err, output)
	}
}
