// Code generated by logcopter-gen; DO NOT EDIT.

package sqlite

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.ragkit.rag.content.sqlite")
