// Code generated by logcopter-gen; DO NOT EDIT.

package representations

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.ragkit.rag.representations")
