// Code generated by logcopter-gen; DO NOT EDIT.

package jsonutil

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.ragkit.internal.jsonutil")
